"""meeting up

Revision ID: 16c009fdf67b
Revises: 1a90fce1ecda
Create Date: 2023-12-22 19:08:51.999534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c009fdf67b'
down_revision: Union[str, None] = '1a90fce1ecda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('doctor_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'meeting', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'doctor_id')
    # ### end Alembic commands ###
