"""meeting

Revision ID: 1a90fce1ecda
Revises: 722e7e06dde9
Create Date: 2023-12-11 21:48:40.338186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a90fce1ecda'
down_revision: Union[str, None] = '722e7e06dde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pacient_id', sa.UUID(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('meet_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pacient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_id'), 'meeting', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_id'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
