"""meeting doctor username

Revision ID: 3cbab73361e9
Revises: 16c009fdf67b
Create Date: 2023-12-22 21:12:18.261073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbab73361e9'
down_revision: Union[str, None] = '16c009fdf67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('doctor_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'doctor_username')
    # ### end Alembic commands ###
